import os
import hashlib
import base64
import secrets
import time
import jwt
from typing import Optional, Dict, List
from sqlalchemy import create_engine, text

# Load environment variables from .env file if it exists
if os.path.exists(".env"):
    with open(".env") as f:
        for line in f:
            if line.strip() and not line.startswith("#"):
                parts = line.strip().split("=", 1)
                if len(parts) == 2:
                    key, val = parts
                    os.environ[key.strip()] = val.strip().strip('"').strip("'")

# 1. Read database configuration url from environment (fallback to SQLite users.db locally)
DATABASE_URL = os.getenv("AUTH_DATABASE_URL", "sqlite:///users.db")

# Create connection pool engine. Add pool_pre_ping to check connection health.
# If connecting to a PostgreSQL pooler (like Neon), disable statement preparation if using transaction poolers.
connect_args = {}
if DATABASE_URL.startswith("sqlite"):
    # SQLite requires separate thread access constraints disabled in FastAPI environments
    connect_args["check_same_thread"] = False

engine = create_engine(DATABASE_URL, connect_args=connect_args, pool_pre_ping=True)

def init_auth_db():
    """
    Initializes users and saved connections tables on the database.
    Supports autoincrement keywords correctly on SQLite, MySQL, and PostgreSQL.
    """
    is_sqlite = engine.url.drivername.startswith("sqlite")
    id_type = "INTEGER PRIMARY KEY AUTOINCREMENT" if is_sqlite else "SERIAL PRIMARY KEY"
    
    with engine.begin() as conn:
        # Create users table
        conn.execute(text(f"""
        CREATE TABLE IF NOT EXISTS users (
            id {id_type},
            username VARCHAR(255) UNIQUE NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            name VARCHAR(255),
            email VARCHAR(255) UNIQUE
        );
        """))
        
        # Create saved connections table
        conn.execute(text(f"""
        CREATE TABLE IF NOT EXISTS connections (
            id {id_type},
            user_id INTEGER UNIQUE NOT NULL,
            db_type VARCHAR(50) NOT NULL,
            host VARCHAR(255),
            port INTEGER,
            username VARCHAR(255),
            password VARCHAR(255),
            database VARCHAR(255) NOT NULL,
            ssl_mode VARCHAR(50),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );
        """))
        
        # Run ALTER TABLE migrations in isolated savepoints so that
        # PostgreSQL doesn't abort the whole transaction on "column already exists".
        for col_sql in [
            "ALTER TABLE users ADD COLUMN name VARCHAR(255);",
            "ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE;",
        ]:
            try:
                with conn.begin_nested():
                    conn.execute(text(col_sql))
            except Exception:
                pass

        # Create API keys table (separate savepoint to avoid transaction abort)
        try:
            with conn.begin_nested():
                conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS api_keys (
                    id {id_type},
                    user_id INTEGER NOT NULL,
                    key_hash VARCHAR(64) NOT NULL,
                    prefix VARCHAR(8) NOT NULL,
                    name VARCHAR(255) DEFAULT 'default',
                    created_at INTEGER NOT NULL,
                    last_used_at INTEGER,
                    revoked INTEGER DEFAULT 0,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                );
                """))
        except Exception:
            pass

def hash_password(password: str) -> str:
    """
    Returns the SHA-256 hash representation of a password string.
    """
    return hashlib.sha256(password.encode()).hexdigest()

def encode_password(password: str) -> str:
    """
    Base64 encodes password strings for basic obfuscation.
    """
    if not password:
        return ""
    return base64.b64encode(password.encode()).decode()

def decode_password(encoded: str) -> str:
    """
    Decodes base64 obfuscated password strings.
    """
    if not encoded:
        return ""
    try:
        return base64.b64decode(encoded.encode()).decode()
    except Exception:
        return ""

def create_user(username: str, password: str, name: str, email: str) -> Optional[int]:
    """
    Registers a new user record. Returns autogenerated user ID on success, None otherwise.
    """
    pwd_hash = hash_password(password)
    try:
        with engine.begin() as conn:
            if engine.url.drivername.startswith("sqlite"):
                conn.execute(
                    text("INSERT INTO users (username, password_hash, name, email) VALUES (:u, :p, :n, :e);"),
                    {"u": username, "p": pwd_hash, "n": name, "e": email}
                )
                res = conn.execute(text("SELECT last_insert_rowid();"))
                return res.scalar()
            else:
                res = conn.execute(
                    text("INSERT INTO users (username, password_hash, name, email) VALUES (:u, :p, :n, :e) RETURNING id;"),
                    {"u": username, "p": pwd_hash, "n": name, "e": email}
                )
                return res.scalar()
    except Exception:
        return None

def verify_user(username: str, password: str) -> Optional[Dict]:
    """
    Authenticates username and password credentials. Returns user details on success, None otherwise.
    """
    pwd_hash = hash_password(password)
    with engine.connect() as conn:
        res = conn.execute(
            text("SELECT id, username, name, email FROM users WHERE username = :u AND password_hash = :p;"),
            {"u": username, "p": pwd_hash}
        )
        row = res.fetchone()
        if row:
            # Map index correctly supporting fallback username values
            return {
                "id": row[0],
                "username": row[1],
                "name": row[2] or row[1],
                "email": row[3] or ""
            }
    return None

def save_connection(
    user_id: int,
    db_type: str,
    host: Optional[str],
    port: Optional[int],
    username: Optional[str],
    password: Optional[str],
    database: str,
    ssl_mode: Optional[str]
):
    """
    Saves or updates database connection details for a user.
    """
    pwd_enc = encode_password(password)
    
    with engine.begin() as conn:
        # Check if user profile already exists
        check = conn.execute(
            text("SELECT id FROM connections WHERE user_id = :uid;"),
            {"uid": user_id}
        ).fetchone()
        
        if check:
            conn.execute(text("""
                UPDATE connections SET
                    db_type = :db_type,
                    host = :host,
                    port = :port,
                    username = :username,
                    password = :pwd_enc,
                    database = :database,
                    ssl_mode = :ssl_mode
                WHERE user_id = :uid;
            """), {
                "db_type": db_type,
                "host": host,
                "port": port,
                "username": username,
                "pwd_enc": pwd_enc,
                "database": database,
                "ssl_mode": ssl_mode,
                "uid": user_id
            })
        else:
            conn.execute(text("""
                INSERT INTO connections (user_id, db_type, host, port, username, password, database, ssl_mode)
                VALUES (:uid, :db_type, :host, :port, :username, :pwd_enc, :database, :ssl_mode);
            """), {
                "uid": user_id,
                "db_type": db_type,
                "host": host,
                "port": port,
                "username": username,
                "pwd_enc": pwd_enc,
                "database": database,
                "ssl_mode": ssl_mode
            })

def get_connection_profile(user_id: int) -> Optional[Dict]:
    """
    Retrieves saved database connection profile details. Decrypts connection passwords.
    """
    with engine.connect() as conn:
        res = conn.execute(text("""
            SELECT db_type, host, port, username, password, database, ssl_mode
            FROM connections WHERE user_id = :uid;
        """), {"uid": user_id})
        row = res.fetchone()
        
        if row:
            return {
                "db_type": row[0],
                "host": row[1],
                "port": row[2],
                "username": row[3],
                "password": decode_password(row[4]),
                "database": row[5],
                "ssl_mode": row[6]
            }
    return None

# ── JWT Token helpers ──────────────────────────────────────────────

JWT_SECRET = os.getenv("JWT_SECRET", "sg-jwt-secret-change-in-production")
JWT_EXPIRE = int(os.getenv("JWT_EXPIRE_HOURS", "72")) * 3600

def create_token(user_id: int, username: str) -> str:
    payload = {
        "sub": str(user_id),
        "username": username,
        "iat": int(time.time()),
        "exp": int(time.time()) + JWT_EXPIRE,
    }
    return jwt.encode(payload, JWT_SECRET, algorithm="HS256")

def verify_token(token: str) -> Optional[Dict]:
    try:
        payload = jwt.decode(token, JWT_SECRET, algorithms=["HS256"])
        return {"user_id": int(payload["sub"]), "username": payload.get("username")}
    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError:
        return None


# ── API Key helpers ────────────────────────────────────────────────

def create_api_key(user_id: int, name: str = "default") -> Optional[str]:
    """Generate a new API key. Returns the full key (shown once) or None on failure."""
    raw_key = "sg_" + secrets.token_hex(24)
    key_hash = hashlib.sha256(raw_key.encode()).hexdigest()
    prefix = raw_key[:8]
    try:
        with engine.begin() as conn:
            conn.execute(
                text("INSERT INTO api_keys (user_id, key_hash, prefix, name, created_at) VALUES (:uid, :hash, :prefix, :name, :ts)"),
                {"uid": user_id, "hash": key_hash, "prefix": prefix, "name": name, "ts": int(time.time())}
            )
        return raw_key
    except Exception:
        return None

def verify_api_key(raw_key: str) -> Optional[Dict]:
    """Look up an API key. Returns user info if valid, None otherwise."""
    key_hash = hashlib.sha256(raw_key.encode()).hexdigest()
    try:
        with engine.connect() as conn:
            row = conn.execute(
                text("SELECT ak.user_id, u.username FROM api_keys ak JOIN users u ON ak.user_id = u.id WHERE ak.key_hash = :hash AND ak.revoked = 0"),
                {"hash": key_hash}
            ).fetchone()
            if row:
                # Update last_used_at
                conn.execute(
                    text("UPDATE api_keys SET last_used_at = :ts WHERE key_hash = :hash"),
                    {"ts": int(time.time()), "hash": key_hash}
                )
                return {"user_id": row[0], "username": row[1]}
    except Exception:
        pass
    return None

def list_api_keys(user_id: int) -> List[Dict]:
    """List non-revoked API keys for a user (without the full key)."""
    try:
        with engine.connect() as conn:
            rows = conn.execute(
                text("SELECT id, prefix, name, created_at, last_used_at, revoked FROM api_keys WHERE user_id = :uid ORDER BY created_at DESC"),
                {"uid": user_id}
            ).fetchall()
            return [
                {"id": r[0], "prefix": r[1] + "...", "name": r[2], "created_at": r[3], "last_used_at": r[4], "revoked": bool(r[5])}
                for r in rows
            ]
    except Exception:
        return []

def revoke_api_key(key_id: int, user_id: int) -> bool:
    """Revoke an API key by its ID (scoped to the user)."""
    try:
        with engine.begin() as conn:
            conn.execute(
                text("UPDATE api_keys SET revoked = 1 WHERE id = :kid AND user_id = :uid"),
                {"kid": key_id, "uid": user_id}
            )
        return True
    except Exception:
        return False


# Auto-initialize database tables on launch
init_auth_db()
